# Generated by Django 4.0.5 on 2022-06-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_client', models.BigIntegerField(null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_inscription', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.client')),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('marques', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('stock', models.CharField(choices=[('1', '1'), ('10', '10'), ('50', '50'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2500', '2500'), ('5000', '5000'), ('10000', '10000'), ('20000+', '20000+')], max_length=20)),
                ('prix', models.BigIntegerField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.cat_product')),
            ],
        ),
        migrations.CreateModel(
            name='liste_pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.BigIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.commandes')),
                ('produit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drive.produit')),
            ],
        ),
    ]
