# Generated by Django 4.0.5 on 2022-06-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.client'),
        ),
    ]
