# Generated by Django 4.0.5 on 2022-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='num_client',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='num_commande',
            field=models.BigIntegerField(null=True),
        ),
    ]
