# Generated by Django 4.0.5 on 2022-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.CharField(choices=[('1', '1'), ('10', '10'), ('50', '50'), ('100', '100'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('2500', '2500'), ('5000', '5000'), ('10000', '10000'), ('20000+', '20000+')], max_length=10),
        ),
    ]
