# Generated by Django 4.0.5 on 2022-06-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_commandes_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandes',
            old_name='date_inscription',
            new_name='date',
        ),
    ]
