# Generated by Django 4.0.4 on 2022-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_produit_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
